# Generated by Django 5.0.6 on 2024-07-22 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_color_variant_product_size_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupen',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coupen_code', models.CharField(max_length=100)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=100)),
                ('minimum_amount', models.IntegerField(default=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
