# Generated by Django 5.0.6 on 2024-08-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_id',
        ),
    ]
