# Generated by Django 5.0.6 on 2024-07-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_is_paid'),
        ('product', '0004_product_color_variant_product_size_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color_variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sizevariant'),
        ),
    ]
