# Generated by Django 5.0.6 on 2024-07-23 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_cartitem_color_variant_cartitem_size_variant'),
        ('product', '0005_coupen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.coupen'),
        ),
    ]
