# Generated by Django 5.0.6 on 2024-07-23 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cart_coupen'),
        ('product', '0005_coupen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.coupen'),
        ),
    ]
