# Generated by Django 5.0.6 on 2024-08-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_order_items_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
